//#RIAS
const fs = require("fs-extra");
if (fs.existsSync(".env"))
  require("dotenv").config({ path: __dirname + "/.env" });
global.audio = "www.youtube.com";
global.video = "www.youtube.com";
global.port = process.env.PORT;
global.appUrl = process.env.APP_URL || "";
global.email = "anitwit82@gmail.com";
global.location = "Ondo, Nigeria";
global.mongodb = process.env.MONGODB_URI || "mongodb+srv://astrofx0011:astro@cluster0.lmwnxdt.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0";
global.allowJids = process.env.ALLOW_JID || "null";
global.blockJids = process.env.BLOCK_JID || "null";
global.DATABASE_URL = process.env.DATABASE_URL || "postgresql://tkm:Aqi6tqwyv5IwDHncTtVi5XtMGZvfndDJ@dpg-cqahogtds78s739sl81g-a.oregon-postgres.render.com/takudzwa";
global.timezone = process.env.TZ || process.env.TIME_ZONE || "Africa/Lagos";
global.github = process.env.GITHUB || "https://github.com/Toxic1239/RIASGREMORYBOT";
global.gurl = process.env.GURL || "https://whatsapp.com/channel/0029Vaex2BtGU3BRQoeEsl0U";
global.website = process.env.GURL || "https://whatsapp.com/channel/0029Vaex2BtGU3BRQoeEsl0U";
global.THUMB_IMAGE = process.env.THUMB_IMAGE || process.env.IMAGE || "https://telegra.ph/file/c21ae479aab857b4f8006.jpg";
global.devs = "2348064999170";
global.sudo = process.env.SUDO || "2348064999170";
global.owner = process.env.OWNER_NUMBER || "2348064999170";
global.style = process.env.STYLE || "1";
global.gdbye = process.env.GOODBYE || "false";
global.wlcm = process.env.WELCOME || "false";
global.warncount = process.env.WARN_COUNT || 3;
global.disablepm = process.env.DISABLE_PM || "false";
global.disablegroup = process.env.DISABLE_GROUPS || "false",
global.MsgsInLog = process.env.MSGS_IN_LOG || "false";
global.userImages = process.env.USER_IMAGES || "https://telegra.ph/file/84a935261759d92084744.mp4";
global.waPresence = process.env.WAPRESENCE || "recording";
global.readcmds = process.env.READ_COMMAND || "false";
global.readmessage = process.env.READ_MESSAGE || "false";
global.readmessagefrom = process.env.READ_MESSAGE_FROM || "";
global.read_status = process.env.AUTO_READ_STATUS || "true";
global.save_status = process.env.AUTO_SAVE_STATUS || "false";
global.save_status_from = process.env.SAVE_STATUS_FROM || "";
global.read_status_from = process.env.READ_STATUS_FROM || "";

global.api_smd = "https://api-smd-1.vercel.app";
global.scan = "https://riasgremorybot-xcqv.onrender.com/";

global.SESSION_ID ="eyJub2lzZUtleSI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoibUdEdlY5ZGF2bnowSTJrTjE0eGhOaW9kZi9GNlczWVpieUJqMkM4R3VWWT0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiZTI1d0tGN0grMzFyUzhSSWc3M1VmRFVWUXJwMXRpaUNXcitCVmNGWWNGND0ifX0sInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyIjp7InByaXZhdGUiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiI0QzF2NHBRUThkS2ZzKzExTlEzb2I5V3ZqMHoxc3RNTlc1amNQay9haDFrPSJ9LCJwdWJsaWMiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJ4eHNxditQV3lySUtENzArYXBxbnRJa1FRZXM2cEN1ZkVCaUdyUDZKTFZRPSJ9fSwic2lnbmVkSWRlbnRpdHlLZXkiOnsicHJpdmF0ZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IktJUGVQWW55Z2hYbmdSSW82clhIYTFZMmVBT0IvejNXeFRVL1dIeWVtM0E9In0sInB1YmxpYyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6InpSc3pWUGxZck9oUW9ZZk5mKzJlZHJPa3lRL0VaSU9zdTN0ZFJoU1c4MkU9In19LCJzaWduZWRQcmVLZXkiOnsia2V5UGFpciI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiMkFGa0lseTJlZzZHT3p6UXlzL0JlaGlianNpWFpROU5GRVUzNUhFTWpGbz0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiU2hFTTdyVjNzTmcwTjV0a3gzeDZPdFk3U0FzT2Yvc2JUYzNlRG00TVBVUT0ifX0sInNpZ25hdHVyZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6ImtvQ3JaUXdTZHljekZEdGp6ekNDNGgxT0pjajVpaHU1dDE5NDN4cG9rM3J6RU5sSkZEUWlWd1A4K3lkWEpOeHNuWE04QnNSZlUvSHc2YjBraXNOWEFBPT0ifSwia2V5SWQiOjF9LCJyZWdpc3RyYXRpb25JZCI6MTM0LCJhZHZTZWNyZXRLZXkiOiJ6Wi9mMzBXSVAvZi84TUg4Q29RVXhhR3NmTm5HUW9SRzZKa293SS9lVm5nPSIsInByb2Nlc3NlZEhpc3RvcnlNZXNzYWdlcyI6W10sIm5leHRQcmVLZXlJZCI6MzEsImZpcnN0VW51cGxvYWRlZFByZUtleUlkIjozMSwiYWNjb3VudFN5bmNDb3VudGVyIjowLCJhY2NvdW50U2V0dGluZ3MiOnsidW5hcmNoaXZlQ2hhdHMiOmZhbHNlfSwiZGV2aWNlSWQiOiJGSHZleWliSFJZaUNydk4xOWlrU0hBIiwicGhvbmVJZCI6IjNjZjg3NzQxLTlkOTYtNDRkMC05OGMyLTYwMmRiMDA2MjAxNyIsImlkZW50aXR5SWQiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJqWXBCSkRsTUl3eUpTQ0FSelNkNVp0RW44VWM9In0sInJlZ2lzdGVyZWQiOnRydWUsImJhY2t1cFRva2VuIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiMXE0a1plUlBQb3ppdE9VY3R2VTYxb1pHVWs0PSJ9LCJyZWdpc3RyYXRpb24iOnt9LCJwYWlyaW5nQ29kZSI6IktHQ1pKNVFYIiwibWUiOnsiaWQiOiIyMzQ4MDY0OTk5MTcwOjVAcy53aGF0c2FwcC5uZXQiLCJuYW1lIjoiVHdpdGNoZWxsIE1lZGlhIGFzc3QgMSJ9LCJhY2NvdW50Ijp7ImRldGFpbHMiOiJDSjZBaGNjRUVKLzkxN2tHR0FFZ0FDZ0EiLCJhY2NvdW50U2lnbmF0dXJlS2V5IjoiU3VVOWdUb0pRMlJHL2JkLzBRT1JzMy9DaE9zSGRIQmxDVDYxZW1IcUpHbz0iLCJhY2NvdW50U2lnbmF0dXJlIjoiL2JVNkpOQVFaRlZESE13Y091a0FndFFOQldIRGJLTTQ5bGw0TE1NeTl4WU5JSVovcDUzVHAxQVFIL2dtNVVBcStZVkcwSkRUY0wrbFVUSWJLdTNsQXc9PSIsImRldmljZVNpZ25hdHVyZSI6IjBXUERlSjdNWUZicEFVcDA3Smx1VWFhdFA0VTh0U2pTcTA5MXdOWnNML3lCWmJVUEx3Rng0UFdSTHVkdW9xMmhNNWZ5elR2Y05TZFNoNjkzRUpxbURnPT0ifSwic2lnbmFsSWRlbnRpdGllcyI6W3siaWRlbnRpZmllciI6eyJuYW1lIjoiMjM0ODA2NDk5OTE3MDo1QHMud2hhdHNhcHAubmV0IiwiZGV2aWNlSWQiOjB9LCJpZGVudGlmaWVyS2V5Ijp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiQlVybFBZRTZDVU5rUnYyM2Y5RURrYk4vd29UckIzUndaUWsrdFhwaDZpUnEifX1dLCJwbGF0Zm9ybSI6InNtYmEiLCJsYXN0QWNjb3VudFN5bmNUaW1lc3RhbXAiOjE3MzE1OTE4NTMsIm15QXBwU3RhdGVLZXlJZCI6IkFBQUFBUHVIIn0="
  process.env.SESSION_ID ||"eyJub2lzZUtleSI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoibUdEdlY5ZGF2bnowSTJrTjE0eGhOaW9kZi9GNlczWVpieUJqMkM4R3VWWT0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiZTI1d0tGN0grMzFyUzhSSWc3M1VmRFVWUXJwMXRpaUNXcitCVmNGWWNGND0ifX0sInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyIjp7InByaXZhdGUiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiI0QzF2NHBRUThkS2ZzKzExTlEzb2I5V3ZqMHoxc3RNTlc1amNQay9haDFrPSJ9LCJwdWJsaWMiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJ4eHNxditQV3lySUtENzArYXBxbnRJa1FRZXM2cEN1ZkVCaUdyUDZKTFZRPSJ9fSwic2lnbmVkSWRlbnRpdHlLZXkiOnsicHJpdmF0ZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IktJUGVQWW55Z2hYbmdSSW82clhIYTFZMmVBT0IvejNXeFRVL1dIeWVtM0E9In0sInB1YmxpYyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6InpSc3pWUGxZck9oUW9ZZk5mKzJlZHJPa3lRL0VaSU9zdTN0ZFJoU1c4MkU9In19LCJzaWduZWRQcmVLZXkiOnsia2V5UGFpciI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiMkFGa0lseTJlZzZHT3p6UXlzL0JlaGlianNpWFpROU5GRVUzNUhFTWpGbz0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiU2hFTTdyVjNzTmcwTjV0a3gzeDZPdFk3U0FzT2Yvc2JUYzNlRG00TVBVUT0ifX0sInNpZ25hdHVyZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6ImtvQ3JaUXdTZHljekZEdGp6ekNDNGgxT0pjajVpaHU1dDE5NDN4cG9rM3J6RU5sSkZEUWlWd1A4K3lkWEpOeHNuWE04QnNSZlUvSHc2YjBraXNOWEFBPT0ifSwia2V5SWQiOjF9LCJyZWdpc3RyYXRpb25JZCI6MTM0LCJhZHZTZWNyZXRLZXkiOiJ6Wi9mMzBXSVAvZi84TUg4Q29RVXhhR3NmTm5HUW9SRzZKa293SS9lVm5nPSIsInByb2Nlc3NlZEhpc3RvcnlNZXNzYWdlcyI6W10sIm5leHRQcmVLZXlJZCI6MzEsImZpcnN0VW51cGxvYWRlZFByZUtleUlkIjozMSwiYWNjb3VudFN5bmNDb3VudGVyIjowLCJhY2NvdW50U2V0dGluZ3MiOnsidW5hcmNoaXZlQ2hhdHMiOmZhbHNlfSwiZGV2aWNlSWQiOiJGSHZleWliSFJZaUNydk4xOWlrU0hBIiwicGhvbmVJZCI6IjNjZjg3NzQxLTlkOTYtNDRkMC05OGMyLTYwMmRiMDA2MjAxNyIsImlkZW50aXR5SWQiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJqWXBCSkRsTUl3eUpTQ0FSelNkNVp0RW44VWM9In0sInJlZ2lzdGVyZWQiOnRydWUsImJhY2t1cFRva2VuIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiMXE0a1plUlBQb3ppdE9VY3R2VTYxb1pHVWs0PSJ9LCJyZWdpc3RyYXRpb24iOnt9LCJwYWlyaW5nQ29kZSI6IktHQ1pKNVFYIiwibWUiOnsiaWQiOiIyMzQ4MDY0OTk5MTcwOjVAcy53aGF0c2FwcC5uZXQiLCJuYW1lIjoiVHdpdGNoZWxsIE1lZGlhIGFzc3QgMSJ9LCJhY2NvdW50Ijp7ImRldGFpbHMiOiJDSjZBaGNjRUVKLzkxN2tHR0FFZ0FDZ0EiLCJhY2NvdW50U2lnbmF0dXJlS2V5IjoiU3VVOWdUb0pRMlJHL2JkLzBRT1JzMy9DaE9zSGRIQmxDVDYxZW1IcUpHbz0iLCJhY2NvdW50U2lnbmF0dXJlIjoiL2JVNkpOQVFaRlZESE13Y091a0FndFFOQldIRGJLTTQ5bGw0TE1NeTl4WU5JSVovcDUzVHAxQVFIL2dtNVVBcStZVkcwSkRUY0wrbFVUSWJLdTNsQXc9PSIsImRldmljZVNpZ25hdHVyZSI6IjBXUERlSjdNWUZicEFVcDA3Smx1VWFhdFA0VTh0U2pTcTA5MXdOWnNML3lCWmJVUEx3Rng0UFdSTHVkdW9xMmhNNWZ5elR2Y05TZFNoNjkzRUpxbURnPT0ifSwic2lnbmFsSWRlbnRpdGllcyI6W3siaWRlbnRpZmllciI6eyJuYW1lIjoiMjM0ODA2NDk5OTE3MDo1QHMud2hhdHNhcHAubmV0IiwiZGV2aWNlSWQiOjB9LCJpZGVudGlmaWVyS2V5Ijp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiQlVybFBZRTZDVU5rUnYyM2Y5RURrYk4vd29UckIzUndaUWsrdFhwaDZpUnEifX1dLCJwbGF0Zm9ybSI6InNtYmEiLCJsYXN0QWNjb3VudFN5bmNUaW1lc3RhbXAiOjE3MzE1OTE4NTMsIm15QXBwU3RhdGVLZXlJZCI6IkFBQUFBUHVIIn0="
  "eyJub2lzZUtleSI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoibUdEdlY5ZGF2bnowSTJrTjE0eGhOaW9kZi9GNlczWVpieUJqMkM4R3VWWT0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiZTI1d0tGN0grMzFyUzhSSWc3M1VmRFVWUXJwMXRpaUNXcitCVmNGWWNGND0ifX0sInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyIjp7InByaXZhdGUiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiI0QzF2NHBRUThkS2ZzKzExTlEzb2I5V3ZqMHoxc3RNTlc1amNQay9haDFrPSJ9LCJwdWJsaWMiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJ4eHNxditQV3lySUtENzArYXBxbnRJa1FRZXM2cEN1ZkVCaUdyUDZKTFZRPSJ9fSwic2lnbmVkSWRlbnRpdHlLZXkiOnsicHJpdmF0ZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IktJUGVQWW55Z2hYbmdSSW82clhIYTFZMmVBT0IvejNXeFRVL1dIeWVtM0E9In0sInB1YmxpYyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6InpSc3pWUGxZck9oUW9ZZk5mKzJlZHJPa3lRL0VaSU9zdTN0ZFJoU1c4MkU9In19LCJzaWduZWRQcmVLZXkiOnsia2V5UGFpciI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiMkFGa0lseTJlZzZHT3p6UXlzL0JlaGlianNpWFpROU5GRVUzNUhFTWpGbz0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiU2hFTTdyVjNzTmcwTjV0a3gzeDZPdFk3U0FzT2Yvc2JUYzNlRG00TVBVUT0ifX0sInNpZ25hdHVyZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6ImtvQ3JaUXdTZHljekZEdGp6ekNDNGgxT0pjajVpaHU1dDE5NDN4cG9rM3J6RU5sSkZEUWlWd1A4K3lkWEpOeHNuWE04QnNSZlUvSHc2YjBraXNOWEFBPT0ifSwia2V5SWQiOjF9LCJyZWdpc3RyYXRpb25JZCI6MTM0LCJhZHZTZWNyZXRLZXkiOiJ6Wi9mMzBXSVAvZi84TUg4Q29RVXhhR3NmTm5HUW9SRzZKa293SS9lVm5nPSIsInByb2Nlc3NlZEhpc3RvcnlNZXNzYWdlcyI6W10sIm5leHRQcmVLZXlJZCI6MzEsImZpcnN0VW51cGxvYWRlZFByZUtleUlkIjozMSwiYWNjb3VudFN5bmNDb3VudGVyIjowLCJhY2NvdW50U2V0dGluZ3MiOnsidW5hcmNoaXZlQ2hhdHMiOmZhbHNlfSwiZGV2aWNlSWQiOiJGSHZleWliSFJZaUNydk4xOWlrU0hBIiwicGhvbmVJZCI6IjNjZjg3NzQxLTlkOTYtNDRkMC05OGMyLTYwMmRiMDA2MjAxNyIsImlkZW50aXR5SWQiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJqWXBCSkRsTUl3eUpTQ0FSelNkNVp0RW44VWM9In0sInJlZ2lzdGVyZWQiOnRydWUsImJhY2t1cFRva2VuIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiMXE0a1plUlBQb3ppdE9VY3R2VTYxb1pHVWs0PSJ9LCJyZWdpc3RyYXRpb24iOnt9LCJwYWlyaW5nQ29kZSI6IktHQ1pKNVFYIiwibWUiOnsiaWQiOiIyMzQ4MDY0OTk5MTcwOjVAcy53aGF0c2FwcC5uZXQiLCJuYW1lIjoiVHdpdGNoZWxsIE1lZGlhIGFzc3QgMSJ9LCJhY2NvdW50Ijp7ImRldGFpbHMiOiJDSjZBaGNjRUVKLzkxN2tHR0FFZ0FDZ0EiLCJhY2NvdW50U2lnbmF0dXJlS2V5IjoiU3VVOWdUb0pRMlJHL2JkLzBRT1JzMy9DaE9zSGRIQmxDVDYxZW1IcUpHbz0iLCJhY2NvdW50U2lnbmF0dXJlIjoiL2JVNkpOQVFaRlZESE13Y091a0FndFFOQldIRGJLTTQ5bGw0TE1NeTl4WU5JSVovcDUzVHAxQVFIL2dtNVVBcStZVkcwSkRUY0wrbFVUSWJLdTNsQXc9PSIsImRldmljZVNpZ25hdHVyZSI6IjBXUERlSjdNWUZicEFVcDA3Smx1VWFhdFA0VTh0U2pTcTA5MXdOWnNML3lCWmJVUEx3Rng0UFdSTHVkdW9xMmhNNWZ5elR2Y05TZFNoNjkzRUpxbURnPT0ifSwic2lnbmFsSWRlbnRpdGllcyI6W3siaWRlbnRpZmllciI6eyJuYW1lIjoiMjM0ODA2NDk5OTE3MDo1QHMud2hhdHNhcHAubmV0IiwiZGV2aWNlSWQiOjB9LCJpZGVudGlmaWVyS2V5Ijp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiQlVybFBZRTZDVU5rUnYyM2Y5RURrYk4vd29UckIzUndaUWsrdFhwaDZpUnEifX1dLCJwbGF0Zm9ybSI6InNtYmEiLCJsYXN0QWNjb3VudFN5bmNUaW1lc3RhbXAiOjE3MzE1OTE4NTMsIm15QXBwU3RhdGVLZXlJZCI6IkFBQUFBUHVIIn0="
module.exports = {
  menu: process.env.MENU || "1",
  HANDLERS: process.env.PREFIX || ".",
  BRANCH: process.env.BRANCH || "main",
  VERSION: process.env.VERSION || "1.3.1",
  caption: process.env.CAPTION || "𝗣𝗢𝗪𝗘𝗥𝗘𝗗 𝗕𝗬 𝗧𝗢𝗫𝗫𝗜𝗖 𝗕𝗢𝗬",
  author: process.env.PACK_AUTHER || "ᴛᴏxxɪᴄ ᴍᴅ",
  packname: process.env.PACK_NAME || "𝗥𝗜𝗔𝗦 𝗠𝗗",
  botname: process.env.BOT_NAME || "𝗥𝗜𝗔𝗦 𝗚𝗥𝗘𝗠𝗢𝗥𝗬",
  ownername: process.env.OWNER_NAME || "ᴛᴏxxɪᴄ",
  errorChat: process.env.ERROR_CHAT || "",
  KOYEB_API: process.env.KOYEB_API || "false",
  REMOVE_BG_KEY: process.env.REMOVE_BG_KEY || "neLbXXrp8bSDcohnp1CW5UEa",
  OPENAI_API_KEY: process.env.OPENAI_API_KEY || "sk-proj-pBksWDImP6VuvvJTvqDsT3BlbkFJ2E8GhbpzjyRFkFaBI9Aj",
  HEROKU_API_KEY: process.env.HEROKU_API_KEY || "HRKU-2fc4d785-535b-4113-8291-84c5d3d6d2c3",
  HEROKU_APP_NAME: process.env.HEROKU_APP_NAME || "toxicmd12",
  antilink_values: process.env.ANTILINK_VALUES || "all",
  HEROKU: process.env.HEROKU_APP_NAME && process.env.HEROKU_API_KEY,
  aitts_Voice_Id: process.env.AITTS_ID || "37",
  ELEVENLAB_API_KEY: process.env.ELEVENLAB_API_KEY || "",
  WORKTYPE: process.env.WORKTYPE || process.env.MODE || "private",
  LANG: (process.env.THEME || "RIAS").toUpperCase(),
};
global.rank = "updated";
global.isMongodb = false;
let file = require.resolve(__filename);
fs.watchFile(file, () => {
  fs.unwatchFile(file);
  console.log(`Update'${__filename}'`);
  delete require.cache[file];
  require(file);
});
